# Generated by Django 2.1.3 on 2018-11-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.TextField()),
                ('bairro', models.TextField()),
                ('rua', models.TextField()),
                ('nome', models.TextField()),
                ('area_min', models.IntegerField()),
                ('testada_min', models.IntegerField()),
                ('taxa_ocp', models.TextField()),
                ('taxa_prm', models.IntegerField()),
                ('num_pav', models.IntegerField()),
                ('coef_aprov', models.FloatField()),
            ],
        ),
    ]
