# Generated by Django 2.1.3 on 2018-11-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0002_filtrobaa_tseptico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.TextField()),
                ('nome', models.TextField()),
                ('area', models.FloatField()),
                ('area_planta', models.FloatField()),
                ('num_pav', models.IntegerField()),
                ('num_pessoas', models.IntegerField()),
            ],
        ),
    ]
