# Generated by Django 2.1.3 on 2018-11-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0003_formulario'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulario',
            name='caminho',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
