# Generated by Django 2.1.3 on 2018-11-20 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0004_formulario_caminho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='caminho',
        ),
    ]
