# Generated by Django 2.1.3 on 2018-11-27 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0007_opcaoform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opcaoform',
            old_name='possui_contrucao',
            new_name='possui_construcao',
        ),
    ]
