# Generated by Django 2.1.3 on 2019-04-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0009_formulario_logradouro'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='agua',
            field=models.TextField(default='y'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dados',
            name='esgoto',
            field=models.TextField(default='y'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dados',
            name='lixo',
            field=models.TextField(default='y'),
            preserve_default=False,
        ),
    ]
